jobs:
  - name: kk_build
    type: runSh
    steps:
    integrations:
      key:
        - integrationName: kodekonveyor
          type: sshKey
      generic:
        - integrationName: kkpipeline
      TASK:
          name: build
          runtime:
            options:
              imageName: kodekonveyor/toolchain
              imageTag: 3.6
              options: --rm -e issuetoken -e sonarkey -v $(pwd):/build -w /build
          script:
            - /usr/local/toolchain/tools/Script
            - /usr/local/toolchain/tools/publish
  
